Imports System.ComponentModel.Design.ObjectSelectorEditor

Public Class OutcomesForm
    Dim CurrentOutcome As String
    Dim CurrentDetails As String

    Sub Reload()
        StartForm.Reload()
        CurrentOutcome = Me.Text
        Dim Startline As Integer = Integer.Parse(CurrentOutcome.Split(New Char() {"_"})(0)) + 3
        Dim Endline As Integer = Integer.Parse(CurrentOutcome.Split(New Char() {"_"})(1)) - 1
        Me.Textbox_Name.Text = StartForm.MainTextbox.Lines(Me.Text.Split(New Char() {"_"})(0) + 1).Split(New Char() {"="})(1)
        Me.Listbox_MainList.Items.Clear()
        For Line2 As Int32 = Startline To Endline
            Dim Line = StartForm.MainTextbox.Lines(Line2)
            Dim NewString As String = Str(Line2) + "|"
            NewString += StartForm.MainTextbox.Lines(Line2).Split(New Char() {"="})(0)
            Me.Listbox_MainList.Items.Add(NewString)
        Next
    End Sub

    Private Sub OutcomesForm_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Combobox_MainSelection.SelectedIndex = 0
        Reload()
        CurrentDetails = GetOutcome()
    End Sub

    Function GetOutcome()
        Dim OutcomeData As String = ""
        Dim ArgsCount As Int16 = 1
        Dim OutcomeDesc1 As String = ""
        Dim OutcomeDesc2 As String = ""
        Dim OutcomeDesc3 As String = ""
        Select Case Me.Combobox_MainSelection.Items(Me.Combobox_MainSelection.SelectedIndex)
            Case "Play Music ="
                OutcomeData = "play_music"
                ArgsCount = 1
                OutcomeDesc1 = "File Name, No .ogg"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Gold +"
                OutcomeData = "gold"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Gold Monthly Income +"
                OutcomeData = "gold_monthly_income"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Legacy +"
                OutcomeData = "legacy"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Legacy Monthly +"
                OutcomeData = "legacy_monthly"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Player ="
                OutcomeData = "player_set_civ"
                ArgsCount = 1
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Research +"
                OutcomeData = "research"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Advantage Points +"
                OutcomeData = "advantage_points"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Manpower +"
                OutcomeData = "manpower"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Inflation +"
                OutcomeData = "inflation"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "AI Agression ="
                OutcomeData = "ai_aggression"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Argressive Expansion ="
                OutcomeData = "ae_set"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Capital ="
                OutcomeData = "move_capital"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "War ="
                OutcomeData = "declare_war2"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Alliance ="
                OutcomeData = "add_alliance"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Non Agression Pact ="
                OutcomeData = "add_non_aggression"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Military Access ="
                OutcomeData = "add_military_access"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Guarantee ="
                OutcomeData = "add_guarantee"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Defensive Pact ="
                OutcomeData = "add_defensive_pact"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Truce ="
                OutcomeData = "add_truce"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Goverment ="
                OutcomeData = "change_ideology_civ"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Religion ="
                OutcomeData = "change_religion_civ"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Annex ="
                OutcomeData = "annex"
                ArgsCount = 1
                OutcomeDesc1 = "ID, Split by ;"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Controlled Annex ="
                OutcomeData = "annex_by_civ_from_civ"
                ArgsCount = 1
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = "ID, Split by ;"
            Case "Full Annex ="
                OutcomeData = "annex_civ"
                ArgsCount = 1
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Full Annex By ="
                OutcomeData = "annexed_by_civ"
                ArgsCount = 1
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Puppet ="
                OutcomeData = "make_puppet"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Set Tag ="
                OutcomeData = "set_civ_tag2"
                ArgsCount = 2
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Event ="
                OutcomeData = "run_event"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Add Random General ="
                OutcomeData = "add_general"
                ArgsCount = 1
                OutcomeDesc1 = "Boolean"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Add General ="
                OutcomeData = "add_general3"
                ArgsCount = 1
                OutcomeDesc1 = "Name"
                OutcomeDesc2 = "ATK Boost, -1 for random"
                OutcomeDesc3 = "DEF Boost, -1 for random"
            Case "Add Random Advisor ="
                OutcomeData = "add_advisor"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Add Advisor ="
                OutcomeData = "add_advisor2"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Name"
                OutcomeDesc3 = ""
            Case "Add Ruler ="
                OutcomeData = "add_ruler"
                ArgsCount = 3
                OutcomeDesc1 = "FirstName=LastName"
                OutcomeDesc2 = "IMG Name, No .png"
                OutcomeDesc3 = "D=M=Y"
            Case "Province Economy ="
                OutcomeData = "province_economy"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Economy Capital ="
                OutcomeData = "province_economy_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Economy All ="
                OutcomeData = "province_economy_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Economy ID ="
                OutcomeData = "province_economy_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Number"
                OutcomeDesc3 = ""
            Case "Province Tax Efficency ="
                OutcomeData = "province_tax_efficiency"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Tax Efficency Capital ="
                OutcomeData = "province_tax_efficiency_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Tax Efficency All ="
                OutcomeData = "province_tax_efficiency_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Tax Efficency ID ="
                OutcomeData = "province_tax_efficiency_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Number"
                OutcomeDesc3 = ""
            Case "Province Manpower ="
                OutcomeData = "province_manpower"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Manpower Capital ="
                OutcomeData = "province_manpower_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Manpower All ="
                OutcomeData = "province_manpower_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Manpower ID ="
                OutcomeData = "province_manpower_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Province Growth Rate ="
                OutcomeData = "province_growth_rate"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Growth Rate Capital ="
                OutcomeData = "province_growth_rate_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Growth Rate All ="
                OutcomeData = "province_growth_rate_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Growth Rate ID ="
                OutcomeData = "province_growth_rate_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Province Population ="
                OutcomeData = "province_population"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Population Capital ="
                OutcomeData = "province_population_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Population All ="
                OutcomeData = "province_population_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Population ID ="
                OutcomeData = "province_population_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Number"
                OutcomeDesc3 = ""
            Case "Province Religion ="
                OutcomeData = "province_religion"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Religion Capital ="
                OutcomeData = "province_religion_capital"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Religion All ="
                OutcomeData = "province_religion_all"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Religion ID ="
                OutcomeData = "province_religion_id"
                ArgsCount = 1
                OutcomeDesc1 = "Province ID"
                OutcomeDesc2 = "ID"
                OutcomeDesc3 = ""
            Case "Province Devastation ="
                OutcomeData = "province_devastation"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Devastation Capital ="
                OutcomeData = "province_devastation_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Devastation All ="
                OutcomeData = "province_devastation_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Devastation ID ="
                OutcomeData = "province_devastation_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Number"
                OutcomeDesc3 = ""
            Case "Province Unrest ="
                OutcomeData = "province_unrest"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Unrest Capital ="
                OutcomeData = "province_unrest_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Unrest All ="
                OutcomeData = "province_unrest_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Unrest ID ="
                OutcomeData = "province_unrest_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Number"
                OutcomeDesc3 = ""
            Case "Province Infrastructure ="
                OutcomeData = "province_infrastructure"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Infrastructure Capital ="
                OutcomeData = "province_infrastructure_capital"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Infrastructure All ="
                OutcomeData = "province_infrastructure_all"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Province Infrastructure ID ="
                OutcomeData = "province_infrastructure_id"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Number"
                OutcomeDesc3 = ""
            Case "Add Core ="
                OutcomeData = "province_add_core_civ"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Remove Core ="
                OutcomeData = "province_remove_core_civ"
                ArgsCount = 2
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Civ Tag"
                OutcomeDesc3 = ""
            Case "Add Army ="
                OutcomeData = "add_new_army"
                ArgsCount = 2
                OutcomeDesc1 = "Army ID"
                OutcomeDesc2 = "Unit ID"
                OutcomeDesc3 = ""
            Case "Add Variable ="
                OutcomeData = "add_variable2"
                ArgsCount = 2
                OutcomeDesc1 = "Civ"
                OutcomeDesc2 = "Variable"
                OutcomeDesc3 = ""
            Case "Bonus Duration ="
                OutcomeData = "bonus_duration"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Monthly Income ="
                OutcomeData = "bonus_monthly_income"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Monthly Legacy ="
                OutcomeData = "bonus_monthly_legacy"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Monthly Legacy % ="
                OutcomeData = "bonus_monthly_legacy_percentage"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Maximum Gold ="
                OutcomeData = "bonus_maximum_amount_of_gold"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Tax Efficency ="
                OutcomeData = "bonus_tax_efficiency"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Growth Rate ="
                OutcomeData = "bonus_growth_rate"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Province Maintenance ="
                OutcomeData = "bonus_province_maintenance"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Buildings Maintenance Cost ="
                OutcomeData = "bonus_buildings_maintenance_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Maintenance Cost ="
                OutcomeData = "bonus_maintenance_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Production Efficency ="
                OutcomeData = "bonus_production_efficiency"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Income Production ="
                OutcomeData = "bonus_income_production"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Income Taxation ="
                OutcomeData = "bonus_income_taxation"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Income Economy ="
                OutcomeData = "bonus_income_economy"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Corruption ="
                OutcomeData = "bonus_corruption"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Inflation ="
                OutcomeData = "bonus_inflation"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Research ="
                OutcomeData = "bonus_research"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Research Points ="
                OutcomeData = "bonus_research_points"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Max Manpower ="
                OutcomeData = "bonus_max_manpower"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Max Manpower % ="
                OutcomeData = "bonus_max_manpower_percentage"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Manpower Recovery Speed ="
                OutcomeData = "bonus_manpower_recovery_speed"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Reinforcement Speed ="
                OutcomeData = "bonus_reinforcement_speed"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Army Morale Recovery ="
                OutcomeData = "bonus_army_morale_recovery"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Army Maintenance ="
                OutcomeData = "bonus_army_maintenance"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Recruitment Time ="
                OutcomeData = "bonus_recruitment_time"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Recruit Cost ="
                OutcomeData = "bonus_recruit_army_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Recruit Cost First Line ="
                OutcomeData = "bonus_recruit_army_first_line_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Recruit Cost Second Line ="
                OutcomeData = "bonus_recruit_army_second_line_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Generals ATK ="
                OutcomeData = "bonus_generals_attack"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Generals DEF ="
                OutcomeData = "bonus_generals_defense"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Units ATK ="
                OutcomeData = "bonus_units_attack"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Units DEF ="
                OutcomeData = "bonus_units_defense"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Regiments Limit ="
                OutcomeData = "bonus_regiments_limit"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Battle Width ="
                OutcomeData = "bonus_battle_width"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Discipline ="
                OutcomeData = "bonus_discipline"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Siege Effectiveness ="
                OutcomeData = "bonus_siege_effectiveness"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Max Morale ="
                OutcomeData = "bonus_max_morale"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Army Speed ="
                OutcomeData = "bonus_army_movement_speed"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Manpower Recovery From Disbanding ="
                OutcomeData = "bonus_manpower_recovery_from_disbanded_army"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus War Score ="
                OutcomeData = "bonus_war_score_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Construction Cost ="
                OutcomeData = "bonus_construction_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Administration Building Cost ="
                OutcomeData = "bonus_administration_buildings_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Military Building Cost ="
                OutcomeData = "bonus_military_buildings_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Economy Building Cost ="
                OutcomeData = "bonus_economy_buildings_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Construction Time ="
                OutcomeData = "bonus_construction_time"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Invest Cost ="
                OutcomeData = "bonus_invest_in_economy_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Manpower Cost ="
                OutcomeData = "bonus_increase_manpower_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Tax Efficency Cost ="
                OutcomeData = "bonus_increase_tax_efficiency_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Infrastructure Cost ="
                OutcomeData = "bonus_develop_infrastructure_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Growth Rate Cost ="
                OutcomeData = "bonus_increase_growth_rate_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Diplomacy Points ="
                OutcomeData = "bonus_diplomacy_points"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Relations Modifier ="
                OutcomeData = "bonus_improve_relations_modifier"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Vassals Income ="
                OutcomeData = "bonus_income_from_vassals"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Agressive Expansion ="
                OutcomeData = "bonus_aggressive_expansion"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Core Cost ="
                OutcomeData = "bonus_core_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Religion Cost ="
                OutcomeData = "bonus_religion_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Revolution Risk ="
                OutcomeData = "bonus_revolutionary_risk"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Loan Interest ="
                OutcomeData = "bonus_loan_interest"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Loan Limit ="
                OutcomeData = "bonus_loans_limit"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Characters Age ="
                OutcomeData = "bonus_all_characters_life_expectancy"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Advisors Cost ="
                OutcomeData = "bonus_advisor_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Advisors Max Levels ="
                OutcomeData = "bonus_advisors_max_level"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus General Cost ="
                OutcomeData = "bonus_general_cost"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Bonus Desease Death Rate ="
                OutcomeData = "bonus_disease_death_rate"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Join HRE First Tier ="
                OutcomeData = "join_alliance_special_id_first_tier"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Join HRE Second Tier ="
                OutcomeData = "join_alliance_special_id_second_tier"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Leave HRE ="
                OutcomeData = "leave_alliance_special_id"
                ArgsCount = 1
                OutcomeDesc1 = "Boolean"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Kill Ruler ="
                OutcomeData = "kill_ruler"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Kill Advisor ="
                OutcomeData = "kill_ruler_chance"
                ArgsCount = 1
                OutcomeDesc1 = "%"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Promote Advisor ="
                OutcomeData = "promote_advisor"
                ArgsCount = 1
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Military Academy +"
                OutcomeData = "military_academy"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Military Academy General +"
                OutcomeData = "military_academy_generals"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Capital City +"
                OutcomeData = "capital_city_level"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Court +"
                OutcomeData = "supreme_court"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Reactor +"
                OutcomeData = "nuclear_reactor"
                ArgsCount = 1
                OutcomeDesc1 = "Number"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Explode ="
                OutcomeData = "explode"
                ArgsCount = 1
                OutcomeDesc1 = "Civ Tag"
                OutcomeDesc2 = ""
                OutcomeDesc3 = ""
            Case "Price +"
                OutcomeData = "price_change_up"
                ArgsCount = 3
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Base%=Random%"
                OutcomeDesc3 = "Base%=Random%"
            Case "Price -"
                OutcomeData = "price_change_random_down"
                ArgsCount = 3
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Base%=Random%"
                OutcomeDesc3 = "Base%=Random%"
            Case "Price Group +"
                OutcomeData = "price_change_group_up"
                ArgsCount = 3
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Base%=Random%"
                OutcomeDesc3 = "Base%=Random%"
            Case "Price Group -"
                OutcomeData = "price_change_group_down"
                ArgsCount = 3
                OutcomeDesc1 = "ID"
                OutcomeDesc2 = "Base%=Random%"
                OutcomeDesc3 = "Base%=Random%"
        End Select
        Groupbox_Input1.Visible = False
        Groupbox_Input2.Visible = False
        Groupbox_Input3.Visible = False
        Dim NewString As String = ""
        NewString += OutcomeData
        NewString += ("=" + Me.Textbox_Input1.Text)
        Richtextbox_Desc1.Text = OutcomeDesc1
        Groupbox_Input1.Visible = True
        If ArgsCount >= 2 Then
            NewString += ("=" + Me.Textbox_Input2.Text)
            Richtextbox_Desc2.Text = OutcomeDesc2
            Groupbox_Input2.Visible = True
        End If
        If ArgsCount = 3 Then
            NewString += ("=" + Me.Textbox_Input3.Text)
            Richtextbox_Desc3.Text = OutcomeDesc3
            Groupbox_Input3.Visible = True
        End If
        Return NewString
    End Function

    Private Sub Button_Add_Click(sender As Object, e As EventArgs) Handles Button_Add.Click
        CurrentDetails = GetOutcome()
        Dim Selected As String
        If Me.Listbox_MainList.SelectedIndex = -1 Then
            Selected = "" + Me.Text.Split(New Char() {"_"})(1) + "|add_variable"
        Else
            Selected = Me.Listbox_MainList.Items(Me.Listbox_MainList.SelectedIndex).ToString()
        End If
        Dim Endline = Integer.Parse(Selected.Split(New Char() {"|"})(0)) + 1
        Dim Lines As List(Of String) = StartForm.MainTextbox.Lines.ToList()
        If Me.Listbox_MainList.SelectedIndex = -1 Then
            Lines.Insert(Endline - 1, CurrentDetails)
        Else
            Lines.Insert(Endline + 1, CurrentDetails)
        End If
        StartForm.MainTextbox.Text = String.Join(Environment.NewLine, Lines)
        Me.Text = CurrentOutcome.Split(New Char() {"_"})(0) + "_" + Str(Int(CurrentOutcome.Split(New Char() {"_"})(1) + 1))
        Reload()
        Listbox_MainList_SelectedIndexChanged(sender, e)
    End Sub

    Private Sub Button_Delete_Click(sender As Object, e As EventArgs) Handles Button_Delete.Click
        CurrentDetails = GetOutcome()
        Dim Selected = Me.Listbox_MainList.Items(Me.Listbox_MainList.SelectedIndex).ToString()
        Dim Startline = Selected.Split(New Char() {"|"})(0)
        Dim Lines As List(Of String) = StartForm.MainTextbox.Lines.ToList()
        Lines.RemoveAt(Startline)
        StartForm.MainTextbox.Text = String.Join(Environment.NewLine(), Lines)
        Me.Text = Me.Text.Split(New Char() {"_"})(0) + "_" + Str(Integer.Parse(Me.Text.Split(New Char() {"_"})(1) - 1))
        Reload()
        Listbox_MainList_SelectedIndexChanged(sender, e)
    End Sub

    Private Sub Combobox_MainSelection_SelectedIndexChanged(sender As Object, e As EventArgs) Handles Combobox_MainSelection.SelectedIndexChanged
        CurrentDetails = GetOutcome()
    End Sub

    Private Sub Listbox_MainList_SelectedIndexChanged(sender As Object, e As EventArgs) Handles Listbox_MainList.SelectedIndexChanged
        If Me.Listbox_MainList.SelectedIndex = -1 Then
            Me.Button_Delete.Enabled = False
        Else
            Me.Button_Delete.Enabled = True
        End If
    End Sub

    Private Sub Textbox_Name_TextChanged(sender As Object, e As EventArgs) Handles Textbox_Name.TextChanged
        Dim Lines = StartForm.MainTextbox.Lines
        Lines(Int(Me.Text.Split(New Char() {"_"})(0)) + 1) = "name=" + Textbox_Name.Text
        StartForm.MainTextbox.Lines = Lines
    End Sub
End Class